inputs:
- class: ZMQPull
  name: listener
  options:
    url: tcp://*:5550

core:
  inbound: ipc:///tmp/ReactOBus.lava.inbound
  outbound: ipc:///tmp/ReactOBus.lava.outbound

reactor:
  workers: 100   # Not used for the moment
  rules:
  - name: org.reactobus
    match:
      field: username
      patterns: 'kernel-ci'
    exec:
      path: /home/buildslave/lava-ci/reactobus-job-parser.py
      timeout: 60
      args:
      - --topic
      - $topic
      - --api
      - https://staging-api.kernelci.org
      - --config
      - /home/buildslave/kernelci-labs.cfg
      - stdin:$data
